# Generated by Django 4.1.4 on 2023-01-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='course_id',
            new_name='Course_id',
        ),
        migrations.RenameField(
            model_name='issue_book',
            old_name='Stud_Name',
            new_name='Student_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stud_sem',
            new_name='Student_Sem',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stud_course',
            new_name='Student_course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stud_name',
            new_name='Student_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stud_password',
            new_name='Student_password',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stud_phno',
            new_name='Student_phno',
        ),
        migrations.AlterField(
            model_name='issue_book',
            name='End_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='issue_book',
            name='Start_date',
            field=models.DateField(),
        ),
    ]
